name: Linux build
on:
  workflow_call:
    inputs:
      repository:
        default: ${{ github.repository }}
        required: false
        type: string

jobs:
  build:
    runs-on: ubuntu-26.04
    strategy:
      fail-fast: false
      matrix:
        compiler: [gcc, clang]
        include:
          - compiler: gcc
            cxx_compiler: g++
          - compiler: clang
            cxx_compiler: clang++
    env:
      CC: ${{ matrix.compiler }}
      CXX: ${{ matrix.cxx_compiler }}
      boost_version: 1.89.0
      BOOST_ROOT: ${{ github.workspace }}/deps/boost-1.89.0
      boost_libs: regex
    
    steps:
      - name: Checkout last commit
        uses: actions/checkout@v7
        with:
          repository: ${{ inputs.repository }}

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y \
            libgoogle-glog-dev \
            libleveldb-dev \
            libmarisa-dev \
            libopencc-dev \
            libunwind-dev \
            libyaml-cpp-dev \
            libgtest-dev \
            ninja-build

      - name: Install Boost
        run: ./install-boost.sh

      - name: Build and test
        run: make test
        env:
          CMAKE_GENERATOR: Ninja
